/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases.InterfaceMethods.Admin;

import Clases.InterfaceMethods.ConnectDbInterface;
import Clases.InterfaceMethods.Verificar;
import Clases.Util.Messages;
import javax.swing.JPanel;

/**
 *
 * @author Clases
 */
public class EjercicioPanel extends JPanel implements Verificar, ConnectDbInterface{

    public EjercicioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        cbIntensidad = new javax.swing.JComboBox();
        cbAreaDelCuerp = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtCalorias = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaADC = new javax.swing.JTextArea();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 230, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Descripción:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Intensidad:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Areas del Cuerpo:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        txtAreaDescripcion.setColumns(28);
        txtAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 230, -1));
        jPanel2.add(cbIntensidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 230, -1));

        cbAreaDelCuerp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbAreaDelCuerp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 230, -1));

        jLabel6.setText("Calorias:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, -1));
        jPanel2.add(txtCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 100, -1));
        jPanel2.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        txtAreaADC.setColumns(20);
        txtAreaADC.setRows(5);
        jScrollPane3.setViewportView(txtAreaADC);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 230, -1));

        jScrollPane2.setViewportView(jPanel2);

        add(jScrollPane2);

    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox cbAreaDelCuerp;
    private javax.swing.JComboBox cbIntensidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextArea txtAreaADC;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtCalorias;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration 

    @Override
    public boolean verificarDatos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean datosVacios() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean escribirDatosDB() {
        Messages.errorMessage("Se escribieron los datos");
        return false;
    }
    
    
}
