/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesAdministrador.ingresoDatos;

import Clases.InterfaceMethods.Admin.FacturaCallback;
import Clases.InterfaceMethods.Admin.MembresiaCallback;
import Clases.InterfaceMethods.ConnectDbInterface;
import Clases.InterfaceMethods.Verificar;
import Clases.Util.SpringUtilities;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDesktopPane;
import javax.swing.JPanel;
import javax.swing.SpringLayout;

/**
 *
 * @author Clases
 */
public class userNewPanel extends JPanel implements ActionListener, ConnectDbInterface, Verificar{
    private JDesktopPane ventana;
    
    public userNewPanel(JDesktopPane vtn) 
    {
        ventana = vtn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        membresiaRbGroup = new javax.swing.ButtonGroup();
        facturaRbGroup = new javax.swing.ButtonGroup();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        lblCuidad = new javax.swing.JLabel();
        txtCuidad = new javax.swing.JTextField();
        lblPais = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        lblEstatura = new javax.swing.JLabel();
        cbEstatura = new javax.swing.JComboBox();
        lblMembresia = new javax.swing.JLabel();
        lblFactura = new javax.swing.JLabel();
        panelMembr = new javax.swing.JPanel();
        btnRbMenSi = new javax.swing.JRadioButton();
        btnRbMemNo = new javax.swing.JRadioButton();
        panelFactura = new javax.swing.JPanel();
        btnRbFactSi = new javax.swing.JRadioButton();
        btnRbFactNo = new javax.swing.JRadioButton();
        panelPesoMeta = new javax.swing.JPanel();
        lblPesoMeta = new javax.swing.JLabel();
        txtPesoMeta = new javax.swing.JTextField();
        panelPesoInicial = new javax.swing.JPanel();
        lblPesoIni = new javax.swing.JLabel();
        txtPesoIni = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        panelEstatura = new javax.swing.JPanel();
        panelEdad = new javax.swing.JPanel();
        
        setLayout(new SpringLayout());

        lblId.setText("ID:");
        add(lblId);

        txtId.setEditable(false);
        add(txtId);

        lblNombre.setText("Nombre:");
        add(lblNombre);
        add(txtNombre);

        lblEmail.setText("Email:");
        add(lblEmail);
        add(txtEmail);

        lblDireccion.setText("Direccion");
        add(lblDireccion);

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDireccion);

        add(jScrollPane1);

        lblCuidad.setLabelFor(txtCuidad);
        lblCuidad.setText("Cuidad");
        add(lblCuidad);
        add(txtCuidad);

        lblPais.setLabelFor(txtPais);
        lblPais.setText("Pais");
        add(lblPais);
        add(txtPais);

        panelEstatura.setLayout(new javax.swing.BoxLayout(panelEstatura, javax.swing.BoxLayout.LINE_AXIS));

        lblEstatura.setLabelFor(cbEstatura);
        lblEstatura.setText("Estatura (cm)");
        lblEstatura.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        panelEstatura.add(lblEstatura);

        cbEstatura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelEstatura.add(cbEstatura);

        add(panelEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, 20));

        panelEdad.setLayout(new javax.swing.BoxLayout(panelEdad, javax.swing.BoxLayout.LINE_AXIS));

        lblEdad.setText("Edad:");
        lblEdad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        panelEdad.add(lblEdad);
        panelEdad.add(txtEdad);

        add(panelEdad);
        
        panelPesoMeta.setLayout(new javax.swing.BoxLayout(panelPesoMeta, javax.swing.BoxLayout.LINE_AXIS));

        lblPesoMeta.setLabelFor(txtPesoMeta);
        lblPesoMeta.setText("Peso Meta(lbs)");
        lblPesoMeta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        panelPesoMeta.add(lblPesoMeta);
        panelPesoMeta.add(txtPesoMeta);

        add(panelPesoMeta);

        panelPesoInicial.setLayout(new javax.swing.BoxLayout(panelPesoInicial, javax.swing.BoxLayout.LINE_AXIS));

        lblPesoIni.setLabelFor(txtPesoIni);
        lblPesoIni.setText("Peso Inicial(lbs)");
        lblPesoIni.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        panelPesoInicial.add(lblPesoIni);
        panelPesoInicial.add(txtPesoIni);

        add(panelPesoInicial);

        lblMembresia.setLabelFor(panelPesoMeta);
        lblMembresia.setText("Membresia:");
        add(lblMembresia);

        lblFactura.setLabelFor(panelMembr);
        lblFactura.setText("Factura:");
        add(lblFactura);

        panelMembr.setLayout(new javax.swing.BoxLayout(panelMembr, javax.swing.BoxLayout.LINE_AXIS));

        membresiaRbGroup.add(btnRbMenSi);
        btnRbMenSi.setActionCommand("rbMembreSi");
        btnRbMenSi.setText("Si");
        btnRbMenSi.addActionListener(this);
        panelMembr.add(btnRbMenSi);

        membresiaRbGroup.add(btnRbMemNo);
        btnRbMemNo.setText("No");
        btnRbFactNo.setEnabled(true);
        panelMembr.add(btnRbMemNo);

        add(panelMembr);

        panelFactura.setLayout(new javax.swing.BoxLayout(panelFactura, javax.swing.BoxLayout.LINE_AXIS));

        facturaRbGroup.add(btnRbFactSi);
        btnRbFactSi.setActionCommand("rbFactSi");
        btnRbFactSi.setText("Si");
        btnRbFactSi.addActionListener(this);
        panelFactura.add(btnRbFactSi);

        facturaRbGroup.add(btnRbFactNo);
        btnRbFactNo.setText("No");
        btnRbFactNo.setEnabled(true);
        panelFactura.add(btnRbFactNo);

        add(panelFactura);

        SpringUtilities.makeCompactGrid(this,
                                        10, 2, //Filas, columnas
                                        6, 6, //initX, initY
                                        6, 6); //xPad, yPad
       
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton btnRbFactNo;
    private javax.swing.JRadioButton btnRbFactSi;
    private javax.swing.JRadioButton btnRbMemNo;
    private javax.swing.JRadioButton btnRbMenSi;
    private javax.swing.JComboBox cbEstatura;
    private javax.swing.ButtonGroup facturaRbGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCuidad;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstatura;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMembresia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPesoIni;
    private javax.swing.JLabel lblPesoMeta;
    private javax.swing.ButtonGroup membresiaRbGroup;
    private javax.swing.JPanel panelFactura;
    private javax.swing.JPanel panelMembr;
    private javax.swing.JPanel panelPesoInicial;
    private javax.swing.JPanel panelPesoMeta;
    private javax.swing.JPanel panelEdad;
    private javax.swing.JPanel panelEstatura;
    private javax.swing.JTextField txtCuidad;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPesoIni;
    private javax.swing.JTextField txtPesoMeta;
    // End of variables declaration  

    @Override
    public void actionPerformed(ActionEvent e) {
        String txt = e.getActionCommand();
        switch (txt){
            case "rbMembreSi":{
                MembresiaCallback memCb = new MembresiaCallback();
                memCb.mnuBtnNuevMembActionPerformed(e, ventana);
            }break;
            case "rbFactSi":{
                FacturaCallback factCb = new FacturaCallback();
                factCb.mnuBtnNuevFacturaActionPerformed(e, ventana);
            }break;
        }
    }

    @Override
    public boolean verificarEscrituraDB() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean escribirDatosDB() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean verificarLecturaDB() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean leerDatosDB() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean verificarDatos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean datosVacios() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
