/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesAdministrador;

/**
 *
 * @author Clases
 */
public class usuarioNuevoPanel extends javax.swing.JPanel {

    /**
     * Creates new form usuarioNuevoPanel
     */
    public usuarioNuevoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        membresiaRbGroup = new javax.swing.ButtonGroup();
        facturaRbGroup = new javax.swing.ButtonGroup();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        lblCuidad = new javax.swing.JLabel();
        txtCuidad = new javax.swing.JTextField();
        lblPais = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        lblMembresia = new javax.swing.JLabel();
        lblFactura = new javax.swing.JLabel();
        panelMembr = new javax.swing.JPanel();
        btnRbMenSi = new javax.swing.JRadioButton();
        btnRbMemNo = new javax.swing.JRadioButton();
        panelFactura = new javax.swing.JPanel();
        btnRbFactSi = new javax.swing.JRadioButton();
        btnRbFactNo = new javax.swing.JRadioButton();
        panelPesoMeta = new javax.swing.JPanel();
        lblPesoMeta = new javax.swing.JLabel();
        txtPesoMeta = new javax.swing.JTextField();
        panelPesoInicial = new javax.swing.JPanel();
        lblPesoIni = new javax.swing.JLabel();
        txtPesoIni = new javax.swing.JTextField();
        panelEstatura = new javax.swing.JPanel();
        lblEstatura = new javax.swing.JLabel();
        cbEstatura = new javax.swing.JComboBox();
        panelEdad = new javax.swing.JPanel();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setText("ID:");
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        txtId.setEditable(false);
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 11, 328, -1));

        lblNombre.setText("Nombre:");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 49, 328, -1));

        lblEmail.setText("Email:");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 87, 328, -1));

        lblDireccion.setText("Direccion");
        add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDireccion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 125, 328, 34));

        lblCuidad.setLabelFor(txtCuidad);
        lblCuidad.setText("Cuidad");
        add(lblCuidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        add(txtCuidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 210, -1));

        lblPais.setLabelFor(txtPais);
        lblPais.setText("Pais");
        add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 210, -1));

        lblMembresia.setLabelFor(panelPesoMeta);
        lblMembresia.setText("Membresia:");
        add(lblMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        lblFactura.setLabelFor(panelMembr);
        lblFactura.setText("Factura:");
        add(lblFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        panelMembr.setLayout(new javax.swing.BoxLayout(panelMembr, javax.swing.BoxLayout.LINE_AXIS));

        membresiaRbGroup.add(btnRbMenSi);
        btnRbMenSi.setText("Si");
        panelMembr.add(btnRbMenSi);

        membresiaRbGroup.add(btnRbMemNo);
        btnRbMemNo.setText("No");
        panelMembr.add(btnRbMemNo);

        add(panelMembr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 130, 30));

        panelFactura.setLayout(new javax.swing.BoxLayout(panelFactura, javax.swing.BoxLayout.LINE_AXIS));

        facturaRbGroup.add(btnRbFactSi);
        btnRbFactSi.setText("Si");
        panelFactura.add(btnRbFactSi);

        facturaRbGroup.add(btnRbFactNo);
        btnRbFactNo.setText("No");
        panelFactura.add(btnRbFactNo);

        add(panelFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 140, 40));

        panelPesoMeta.setLayout(new javax.swing.BoxLayout(panelPesoMeta, javax.swing.BoxLayout.LINE_AXIS));

        lblPesoMeta.setLabelFor(txtPesoMeta);
        lblPesoMeta.setText("Peso Meta(lbs)");
        lblPesoMeta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        panelPesoMeta.add(lblPesoMeta);
        panelPesoMeta.add(txtPesoMeta);

        add(panelPesoMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 150, 20));

        panelPesoInicial.setLayout(new javax.swing.BoxLayout(panelPesoInicial, javax.swing.BoxLayout.LINE_AXIS));

        lblPesoIni.setLabelFor(txtPesoIni);
        lblPesoIni.setText("Peso Inicial(lbs)");
        lblPesoIni.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        panelPesoInicial.add(lblPesoIni);
        panelPesoInicial.add(txtPesoIni);

        add(panelPesoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 20));

        panelEstatura.setLayout(new javax.swing.BoxLayout(panelEstatura, javax.swing.BoxLayout.LINE_AXIS));

        lblEstatura.setLabelFor(cbEstatura);
        lblEstatura.setText("Estatura (cm)");
        lblEstatura.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        panelEstatura.add(lblEstatura);

        cbEstatura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelEstatura.add(cbEstatura);

        add(panelEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, 20));

        panelEdad.setLayout(new javax.swing.BoxLayout(panelEdad, javax.swing.BoxLayout.LINE_AXIS));

        lblEdad.setText("Edad:");
        lblEdad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        panelEdad.add(lblEdad);
        panelEdad.add(txtEdad);

        add(panelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 140, 20));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnRbFactNo;
    private javax.swing.JRadioButton btnRbFactSi;
    private javax.swing.JRadioButton btnRbMemNo;
    private javax.swing.JRadioButton btnRbMenSi;
    private javax.swing.JComboBox cbEstatura;
    private javax.swing.ButtonGroup facturaRbGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCuidad;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstatura;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMembresia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPesoIni;
    private javax.swing.JLabel lblPesoMeta;
    private javax.swing.ButtonGroup membresiaRbGroup;
    private javax.swing.JPanel panelEdad;
    private javax.swing.JPanel panelEstatura;
    private javax.swing.JPanel panelFactura;
    private javax.swing.JPanel panelMembr;
    private javax.swing.JPanel panelPesoInicial;
    private javax.swing.JPanel panelPesoMeta;
    private javax.swing.JTextField txtCuidad;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPesoIni;
    private javax.swing.JTextField txtPesoMeta;
    // End of variables declaration//GEN-END:variables
}
