/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesAdministrador;

import Clases.InterfaceMethods.Admin.EjerciciosCallback;
import Clases.Util.ConectorBDD;
import Imagenes.imageResource;
import Imagenes.imageSize;

/**
 *
 * @author Kevin
 */
public class vtnPrincipalAdm extends javax.swing.JFrame {
    
    private ConectorBDD con;
    /**
     * Creates new form vtnPrincipalAdm
     */
    public vtnPrincipalAdm() {
        
        imgEjercicio = new imageResource("biceps.png", "Ejercicio", imageSize.icon_toolbar);
        imgPersona = new imageResource("male100.png", "UIdesign", imageSize.icon_toolbar);
        imgComida = new imageResource("healthyfood4.png", "Salud", imageSize.icon_toolbar);
        imgDieta = new imageResource("healthyfood6.png", "Salud", imageSize.icon_toolbar);
        imgRutina = new imageResource("weightlift.png", "Ejercicio", imageSize.icon_toolbar);
        
        imgMnuEjercicio = new imageResource("dumbbell.png", "Ejercicio", imageSize.icon_menu);
        imgMnuPersona = new imageResource("male100.png", "UIdesign", imageSize.icon_menu);
        imgMnuComida = new imageResource("healthyfood4.png", "Salud", imageSize.icon_menu);
        imgMnuDieta = new imageResource("healthyfood6.png", "Salud", imageSize.icon_menu);
        imgMnuRutina = new imageResource("weightlift.png", "Ejercicio", imageSize.icon_menu);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnToolAddUsuario = new javax.swing.JButton();
        btnToolAddEjercicio = new javax.swing.JButton();
        btnToolAddComida = new javax.swing.JButton();
        btnToolAgregarADC = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuNuevo = new javax.swing.JMenu();
        mnuBtnNuevEjer = new javax.swing.JMenuItem();
        mnuBtnNuevUsua = new javax.swing.JMenuItem();
        mnuBtnNuevCom = new javax.swing.JMenuItem();
        mnuBtnNuevDiet = new javax.swing.JMenuItem();
        mnuBtnNuevRut = new javax.swing.JMenuItem();
        mnuBtnTblRes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuAbrir = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuBtnGuardar = new javax.swing.JMenuItem();
        mnuBtnGuardarComo = new javax.swing.JMenuItem();
        mnuBtnGuardarTodo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuBtnSalir = new javax.swing.JMenuItem();
        mnuEditar = new javax.swing.JMenu();
        mnubtnUndo = new javax.swing.JMenuItem();
        mnuBtnRedo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuBtnPreferencias = new javax.swing.JMenuItem();
        mnuConectar = new javax.swing.JMenu();
        mnuBtnConectar = new javax.swing.JMenuItem();
        mnuBtnCheckConexion = new javax.swing.JMenuItem();
        mnuBusqueda = new javax.swing.JMenu();
        mnuBtnBusBlanc = new javax.swing.JMenuItem();
        mnuBtnBusPersonas = new javax.swing.JMenuItem();
        mnuBtnBusEjercicios = new javax.swing.JMenuItem();
        mnuBtnBusComidas = new javax.swing.JMenuItem();
        mnuBtnBusRutinas = new javax.swing.JMenuItem();
        mnuBtnBusMembresias = new javax.swing.JMenuItem();
        mnuMostrar = new javax.swing.JMenu();
        mnuBtnMostrarPer = new javax.swing.JMenuItem();
        mnuBtnMostrarEjer = new javax.swing.JMenuItem();
        mnuBtnMostrarRut = new javax.swing.JMenuItem();
        mnuBtnMostrarCom = new javax.swing.JMenuItem();
        mnuBtnMostrarDiet = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnBtnMenbresias = new javax.swing.JMenuItem();
        mnuBtnEstadisticas = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuBtnAyuda = new javax.swing.JMenuItem();
        mnuBtnAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnToolAddUsuario.setIcon(imgPersona);
        btnToolAddUsuario.setToolTipText("Agregar un usuario nuevo");
        btnToolAddUsuario.setFocusable(false);
        btnToolAddUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToolAddUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnToolAddUsuario);

        btnToolAddEjercicio.setIcon(imgEjercicio);
        btnToolAddEjercicio.setToolTipText("Agregar un ejercicio nuevo");
        btnToolAddEjercicio.setFocusable(false);
        btnToolAddEjercicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToolAddEjercicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnToolAddEjercicio);

        btnToolAddComida.setIcon(imgComida);
        btnToolAddComida.setToolTipText("Agregar una comida nueva");
        btnToolAddComida.setFocusable(false);
        btnToolAddComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToolAddComida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnToolAddComida);

        btnToolAgregarADC.setText("Agregar ADC");
        btnToolAgregarADC.setFocusable(false);
        btnToolAgregarADC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToolAgregarADC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnToolAgregarADC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolAgregarADCActionPerformed(evt);
            }
        });
        jToolBar1.add(btnToolAgregarADC);

        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        mnuArchivo.setText("Archivo");

        mnuNuevo.setIcon(imageResource.imageFromResourcesPng("document127.png", "UIdesign", imageSize.icon_menu));
        mnuNuevo.setText("Nuevo");

        mnuBtnNuevEjer.setIcon(imgMnuEjercicio);
        mnuBtnNuevEjer.setText("Ejercicio");
        mnuBtnNuevEjer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnNuevEjerActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuBtnNuevEjer);

        mnuBtnNuevUsua.setIcon(imgMnuPersona);
        mnuBtnNuevUsua.setText("Usuario");
        mnuBtnNuevUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnNuevUsuaActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuBtnNuevUsua);

        mnuBtnNuevCom.setIcon(imgMnuComida);
        mnuBtnNuevCom.setText("Comida");
        mnuBtnNuevCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnNuevComActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuBtnNuevCom);

        mnuBtnNuevDiet.setIcon(imgMnuDieta);
        mnuBtnNuevDiet.setText("Dieta");
        mnuBtnNuevDiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnNuevDietActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuBtnNuevDiet);

        mnuBtnNuevRut.setIcon(imgMnuRutina);
        mnuBtnNuevRut.setText("Rutina");
        mnuBtnNuevRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnNuevRutActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuBtnNuevRut);

        mnuBtnTblRes.setIcon(imageResource.imageFromResourcesPng("chart47.png", "UIdesign", imageSize.icon_menu));
        mnuBtnTblRes.setText("Tabla de Resultados");
        mnuBtnTblRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnTblResActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuBtnTblRes);

        mnuArchivo.add(mnuNuevo);
        mnuArchivo.add(jSeparator1);

        mnuAbrir.setIcon(imageResource.imageFromResourcesPng("opened18.png", "UIdesign", imageSize.icon_menu));
        mnuAbrir.setText("Abrir");
        mnuArchivo.add(mnuAbrir);
        mnuArchivo.add(jSeparator3);

        mnuBtnGuardar.setText("Guardar");
        mnuArchivo.add(mnuBtnGuardar);

        mnuBtnGuardarComo.setText("Guardar Como");
        mnuArchivo.add(mnuBtnGuardarComo);

        mnuBtnGuardarTodo.setText("Guardar Todo");
        mnuArchivo.add(mnuBtnGuardarTodo);
        mnuArchivo.add(jSeparator4);

        mnuBtnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuBtnSalir.setText("Salir");
        mnuArchivo.add(mnuBtnSalir);

        jMenuBar1.add(mnuArchivo);

        mnuEditar.setText("Editar");

        mnubtnUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        mnubtnUndo.setIcon(imageResource.imageFromResourcesPng("update2.png", "UIdesign", imageSize.icon_menu));
        mnubtnUndo.setText("Undo");
        mnuEditar.add(mnubtnUndo);

        mnuBtnRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        mnuBtnRedo.setIcon(imageResource.imageFromResourcesPng("update22.png", "UIdesign", imageSize.icon_menu));
        mnuBtnRedo.setText("Redo");
        mnuEditar.add(mnuBtnRedo);
        mnuEditar.add(jSeparator2);

        mnuBtnPreferencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuBtnPreferencias.setIcon(imageResource.imageFromResourcesPng("settings56.png", "UIdesign", imageSize.icon_menu));
        mnuBtnPreferencias.setText("Preferencias");
        mnuEditar.add(mnuBtnPreferencias);

        jMenuBar1.add(mnuEditar);

        mnuConectar.setText("Conectar");

        mnuBtnConectar.setIcon(imageResource.imageFromResourcesPng("datastorage1.png", "UIdesign", imageSize.icon_menu));
        mnuBtnConectar.setText("Conectar a la base de datos");
        mnuBtnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnConectarActionPerformed(evt);
            }
        });
        mnuConectar.add(mnuBtnConectar);

        mnuBtnCheckConexion.setIcon(imageResource.imageFromResourcesPng("basic14.png", "UIdesign", imageSize.icon_menu));
        mnuBtnCheckConexion.setText("Revisar conexion");
        mnuBtnCheckConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnCheckConexionActionPerformed(evt);
            }
        });
        mnuConectar.add(mnuBtnCheckConexion);

        jMenuBar1.add(mnuConectar);

        mnuBusqueda.setText("Busquedas");

        mnuBtnBusBlanc.setIcon(imageResource.imageFromResourcesPng("magnifier52.png", "UIdesign", imageSize.icon_menu));
        mnuBtnBusBlanc.setText("Busqueda en Blanco");
        mnuBtnBusBlanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnBusBlancActionPerformed(evt);
            }
        });
        mnuBusqueda.add(mnuBtnBusBlanc);

        mnuBtnBusPersonas.setIcon(imgMnuPersona);
        mnuBtnBusPersonas.setText("Busqueda de Personas");
        mnuBtnBusPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnBusPersonasActionPerformed(evt);
            }
        });
        mnuBusqueda.add(mnuBtnBusPersonas);

        mnuBtnBusEjercicios.setIcon(imgMnuEjercicio);
        mnuBtnBusEjercicios.setText("Busqueda de Ejercicios");
        mnuBtnBusEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnBusEjerciciosActionPerformed(evt);
            }
        });
        mnuBusqueda.add(mnuBtnBusEjercicios);

        mnuBtnBusComidas.setIcon(imgMnuComida);
        mnuBtnBusComidas.setText("Busqueda de Comidas");
        mnuBtnBusComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnBusComidasActionPerformed(evt);
            }
        });
        mnuBusqueda.add(mnuBtnBusComidas);

        mnuBtnBusRutinas.setIcon(imgMnuRutina);
        mnuBtnBusRutinas.setText("Busquedas de Rutinas");
        mnuBtnBusRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnBusRutinasActionPerformed(evt);
            }
        });
        mnuBusqueda.add(mnuBtnBusRutinas);

        mnuBtnBusMembresias.setText("Busquedas de Membresias");
        mnuBtnBusMembresias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnBusMembresiasActionPerformed(evt);
            }
        });
        mnuBusqueda.add(mnuBtnBusMembresias);

        jMenuBar1.add(mnuBusqueda);

        mnuMostrar.setText("Mostrar");

        mnuBtnMostrarPer.setIcon(imgMnuPersona);
        mnuBtnMostrarPer.setText("Personas");
        mnuBtnMostrarPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnMostrarPerActionPerformed(evt);
            }
        });
        mnuMostrar.add(mnuBtnMostrarPer);

        mnuBtnMostrarEjer.setIcon(imgMnuEjercicio);
        mnuBtnMostrarEjer.setText("Ejercicios");
        mnuBtnMostrarEjer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnMostrarEjerActionPerformed(evt);
            }
        });
        mnuMostrar.add(mnuBtnMostrarEjer);

        mnuBtnMostrarRut.setIcon(imgMnuRutina);
        mnuBtnMostrarRut.setText("Rutinas");
        mnuBtnMostrarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnMostrarRutActionPerformed(evt);
            }
        });
        mnuMostrar.add(mnuBtnMostrarRut);

        mnuBtnMostrarCom.setIcon(imgMnuComida);
        mnuBtnMostrarCom.setText("Comidas");
        mnuBtnMostrarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnMostrarComActionPerformed(evt);
            }
        });
        mnuMostrar.add(mnuBtnMostrarCom);

        mnuBtnMostrarDiet.setIcon(imgMnuDieta);
        mnuBtnMostrarDiet.setText("Dietas");
        mnuBtnMostrarDiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnMostrarDietActionPerformed(evt);
            }
        });
        mnuMostrar.add(mnuBtnMostrarDiet);

        jMenuBar1.add(mnuMostrar);

        mnuReportes.setText("Reportes");

        mnBtnMenbresias.setIcon(imageResource.imageFromResourcesPng("money132.png", "Cobros", imageSize.icon_menu));
        mnBtnMenbresias.setText("Membresias");
        mnuReportes.add(mnBtnMenbresias);

        mnuBtnEstadisticas.setIcon(imageResource.imageFromResourcesPng("chart47.png", "UIdesign", imageSize.icon_menu));
        mnuBtnEstadisticas.setText("Estadisticas");
        mnuReportes.add(mnuBtnEstadisticas);

        jMenuBar1.add(mnuReportes);

        mnuAyuda.setText("Ayuda");

        mnuBtnAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuBtnAyuda.setText("Contenidos de Ayuda");
        mnuAyuda.add(mnuBtnAyuda);

        mnuBtnAcercade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuBtnAcercade.setText("Acerca de");
        mnuAyuda.add(mnuBtnAcercade);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToolAgregarADCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolAgregarADCActionPerformed
        VtnAreaDelCuerpo vtnADC = new VtnAreaDelCuerpo(null, con);
    }//GEN-LAST:event_btnToolAgregarADCActionPerformed

    private void mnuBtnNuevEjerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnNuevEjerActionPerformed
        // TODO add your handling code here:
        EjerciciosCallback ejcb = new EjerciciosCallback();
        ejcb.mnuBtnNuevEjerActionPerformed(evt, jDesktopPane1);
    }//GEN-LAST:event_mnuBtnNuevEjerActionPerformed

    private void mnuBtnNuevUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnNuevUsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnNuevUsuaActionPerformed

    private void mnuBtnNuevComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnNuevComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnNuevComActionPerformed

    private void mnuBtnNuevDietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnNuevDietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnNuevDietActionPerformed

    private void mnuBtnNuevRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnNuevRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnNuevRutActionPerformed

    private void mnuBtnTblResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnTblResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnTblResActionPerformed

    private void mnuBtnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnConectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnConectarActionPerformed

    private void mnuBtnCheckConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnCheckConexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnCheckConexionActionPerformed

    private void mnuBtnBusBlancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnBusBlancActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnBusBlancActionPerformed

    private void mnuBtnBusPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnBusPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnBusPersonasActionPerformed

    private void mnuBtnBusEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnBusEjerciciosActionPerformed
        // TODO add your handling code here:
         EjerciciosCallback ejcb = new EjerciciosCallback();
         ejcb.mnuBtnBusEjerciciosActionPerformed(evt, jDesktopPane1);
    }//GEN-LAST:event_mnuBtnBusEjerciciosActionPerformed

    private void mnuBtnBusComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnBusComidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnBusComidasActionPerformed

    private void mnuBtnBusRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnBusRutinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnBusRutinasActionPerformed

    private void mnuBtnBusMembresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnBusMembresiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnBusMembresiasActionPerformed

    private void mnuBtnMostrarPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnMostrarPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnMostrarPerActionPerformed

    private void mnuBtnMostrarEjerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnMostrarEjerActionPerformed
        // TODO add your handling code here:
         EjerciciosCallback ejcb = new EjerciciosCallback();
        ejcb.mnuBtnMostrarEjerActionPerformed(evt, jDesktopPane1);
    }//GEN-LAST:event_mnuBtnMostrarEjerActionPerformed

    private void mnuBtnMostrarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnMostrarRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnMostrarRutActionPerformed

    private void mnuBtnMostrarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnMostrarComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnMostrarComActionPerformed

    private void mnuBtnMostrarDietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnMostrarDietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBtnMostrarDietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new vtnPrincipalAdm().setVisible(true);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Autogen-Variable Declaration Code">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnToolAddComida;
    private javax.swing.JButton btnToolAddEjercicio;
    private javax.swing.JButton btnToolAddUsuario;
    private javax.swing.JButton btnToolAgregarADC;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnBtnMenbresias;
    private javax.swing.JMenu mnuAbrir;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuBtnAcercade;
    private javax.swing.JMenuItem mnuBtnAyuda;
    private javax.swing.JMenuItem mnuBtnBusBlanc;
    private javax.swing.JMenuItem mnuBtnBusComidas;
    private javax.swing.JMenuItem mnuBtnBusEjercicios;
    private javax.swing.JMenuItem mnuBtnBusMembresias;
    private javax.swing.JMenuItem mnuBtnBusPersonas;
    private javax.swing.JMenuItem mnuBtnBusRutinas;
    private javax.swing.JMenuItem mnuBtnCheckConexion;
    private javax.swing.JMenuItem mnuBtnConectar;
    private javax.swing.JMenuItem mnuBtnEstadisticas;
    private javax.swing.JMenuItem mnuBtnGuardar;
    private javax.swing.JMenuItem mnuBtnGuardarComo;
    private javax.swing.JMenuItem mnuBtnGuardarTodo;
    private javax.swing.JMenuItem mnuBtnMostrarCom;
    private javax.swing.JMenuItem mnuBtnMostrarDiet;
    private javax.swing.JMenuItem mnuBtnMostrarEjer;
    private javax.swing.JMenuItem mnuBtnMostrarPer;
    private javax.swing.JMenuItem mnuBtnMostrarRut;
    private javax.swing.JMenuItem mnuBtnNuevCom;
    private javax.swing.JMenuItem mnuBtnNuevDiet;
    private javax.swing.JMenuItem mnuBtnNuevEjer;
    private javax.swing.JMenuItem mnuBtnNuevRut;
    private javax.swing.JMenuItem mnuBtnNuevUsua;
    private javax.swing.JMenuItem mnuBtnPreferencias;
    private javax.swing.JMenuItem mnuBtnRedo;
    private javax.swing.JMenuItem mnuBtnSalir;
    private javax.swing.JMenuItem mnuBtnTblRes;
    private javax.swing.JMenu mnuBusqueda;
    private javax.swing.JMenu mnuConectar;
    private javax.swing.JMenu mnuEditar;
    private javax.swing.JMenu mnuMostrar;
    private javax.swing.JMenu mnuNuevo;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenuItem mnubtnUndo;
    // End of variables declaration//GEN-END:variables
    // </editor-fold> 
    private imageResource imgPersona;
    private imageResource imgEjercicio;
    private imageResource imgRutina;
    private imageResource imgComida;
    private imageResource imgDieta;
    
    private imageResource imgMnuPersona;
    private imageResource imgMnuEjercicio;
    private imageResource imgMnuRutina;
    private imageResource imgMnuComida;
    private imageResource imgMnuDieta;
    
    public ConectorBDD getCon(){
        return this.con;
    }

}
