/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesAdministrador;

import Clases.Util.ConectorBDD;
import Imagenes.imageResource;
import Imagenes.imageSize;
import java.awt.Dimension;

/**
 *
 * @author Clases
 */
public class vtnPrincipalAdm extends javax.swing.JFrame {
    
    private ConectorBDD con;
    private imageResource tamano;
    /**
     * Creates new form vtnPrincipalAdm
     */
    public vtnPrincipalAdm() {
        tamano = new imageResource();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnAgregarADC = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        mnuBtnNuevEjer = new javax.swing.JMenuItem();
        mnuBtnNuevUsua = new javax.swing.JMenuItem();
        mnuBtnNuevCom = new javax.swing.JMenuItem();
        mnuBtnNuevDiet = new javax.swing.JMenuItem();
        mnuBtnNuevRut = new javax.swing.JMenuItem();
        mnuBtnTblRes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuBtnGuardar = new javax.swing.JMenuItem();
        mnuBtnGuardarComo = new javax.swing.JMenuItem();
        mnuBtnGuardarTodo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuBtnSalir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnubtnUndo = new javax.swing.JMenuItem();
        mnuBtnRedo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuBtnBusBlanc = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuBtnAyuda = new javax.swing.JMenuItem();
        mnuBtnAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(tamano.obtenerImagen(getClass().getResource("/Imagenes/png/UIdesign/male100.png"), imageSize.icon_toolbar));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png/Ejercicio/biceps.png"))); // NOI18N
        jButton2.setText("                                                                                                                                             ");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png/Salud/healthyfood6.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        btnAgregarADC.setText("Agregar ADC");
        btnAgregarADC.setFocusable(false);
        btnAgregarADC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarADC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarADC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarADCActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgregarADC);

        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        jMenu1.setText("Archivo");

        jMenu6.setIcon(tamano.obtenerImagen(getClass().getResource("/Imagenes/png/UIdesign/document127.png"), new Dimension(10,10)));
        jMenu6.setText("Nuevo");

        mnuBtnNuevEjer.setText("Ejercicio");
        jMenu6.add(mnuBtnNuevEjer);

        mnuBtnNuevUsua.setText("Usuario");
        jMenu6.add(mnuBtnNuevUsua);

        mnuBtnNuevCom.setText("Comida");
        jMenu6.add(mnuBtnNuevCom);

        mnuBtnNuevDiet.setText("Dieta");
        jMenu6.add(mnuBtnNuevDiet);

        mnuBtnNuevRut.setText("Rutina");
        jMenu6.add(mnuBtnNuevRut);

        mnuBtnTblRes.setText("Tabla de Resultados");
        jMenu6.add(mnuBtnTblRes);

        jMenu1.add(jMenu6);
        jMenu1.add(jSeparator1);

        jMenu7.setText("Abrir");

        jMenuItem2.setText("jMenuItem2");
        jMenu7.add(jMenuItem2);

        jMenu1.add(jMenu7);
        jMenu1.add(jSeparator3);

        mnuBtnGuardar.setText("Guardar");
        jMenu1.add(mnuBtnGuardar);

        mnuBtnGuardarComo.setText("Guardar Como");
        jMenu1.add(mnuBtnGuardarComo);

        mnuBtnGuardarTodo.setText("Guardar Todo");
        jMenu1.add(mnuBtnGuardarTodo);
        jMenu1.add(jSeparator4);

        mnuBtnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuBtnSalir.setText("Salir");
        jMenu1.add(mnuBtnSalir);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Editar");

        mnubtnUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        mnubtnUndo.setText("Undo");
        jMenu4.add(mnubtnUndo);

        mnuBtnRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        mnuBtnRedo.setText("Redo");
        jMenu4.add(mnuBtnRedo);
        jMenu4.add(jSeparator2);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Preferencias");
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Conectar");

        jMenuItem5.setText("Conectar a la base de datos");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Revisar conexion");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Busquedas");

        mnuBtnBusBlanc.setText("Busqueda en Blanco");
        jMenu5.add(mnuBtnBusBlanc);

        jMenuItem3.setText("Busqueda de Personas");
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Busqueda de Ejercicios");
        jMenu5.add(jMenuItem4);

        jMenuItem8.setText("Busqueda de Comidas");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Busquedas de Rutinas");
        jMenu5.add(jMenuItem9);

        jMenuItem1.setText("Busquedas de Membresias");
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("Mostrar");
        jMenuBar1.add(jMenu8);

        jMenu9.setText("Reportes");
        jMenuBar1.add(jMenu9);

        jMenu3.setText("Ayuda");

        mnuBtnAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuBtnAyuda.setText("Contenidos de Ayuda");
        jMenu3.add(mnuBtnAyuda);

        mnuBtnAcercade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuBtnAcercade.setText("Acerca de");
        jMenu3.add(mnuBtnAcercade);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarADCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarADCActionPerformed
        VtnAreaDelCuerpo vtnADC = new VtnAreaDelCuerpo(null, con);
    }//GEN-LAST:event_btnAgregarADCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnPrincipalAdm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarADC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuBtnAcercade;
    private javax.swing.JMenuItem mnuBtnAyuda;
    private javax.swing.JMenuItem mnuBtnBusBlanc;
    private javax.swing.JMenuItem mnuBtnGuardar;
    private javax.swing.JMenuItem mnuBtnGuardarComo;
    private javax.swing.JMenuItem mnuBtnGuardarTodo;
    private javax.swing.JMenuItem mnuBtnNuevCom;
    private javax.swing.JMenuItem mnuBtnNuevDiet;
    private javax.swing.JMenuItem mnuBtnNuevEjer;
    private javax.swing.JMenuItem mnuBtnNuevRut;
    private javax.swing.JMenuItem mnuBtnNuevUsua;
    private javax.swing.JMenuItem mnuBtnRedo;
    private javax.swing.JMenuItem mnuBtnSalir;
    private javax.swing.JMenuItem mnuBtnTblRes;
    private javax.swing.JMenuItem mnubtnUndo;
    // End of variables declaration//GEN-END:variables
    
    public ConectorBDD getCon(){
        return this.con;
    }

}
